(* Lexical part *)
(* char -> all symbols without "'" *)
digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
let16 = 'A' | 'B' | 'C' | 'D' | 'E' | 'F';
letter = 'G' | 'H' | 'I' | 'J' | 'K' | 'L' | 'M' 
       | 'N' | 'O' | 'P' | 'Q' | 'R' | 'S' | 'T' 
       | 'U' | 'V' | 'W' | 'X' | 'Y' | 'Z' 
       | 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' 
       | 'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' 
       | 'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' 
       | 'v' | 'w' | 'x' | 'y' | 'z' | '_';
id_symbols = '!' | '@' | '#' | '$' | '%' | '^' | '&' | '*' | ':' | '?';
code_mark      = '\';
record_begin   = '/';
record_end     = ';';
quotation_mark = "'";
id     = record_begin, [id_symbols], (letter | let16), {letter | let16 | digit};
byte   = digit | let16, digit | let16;
code   = code_mark, byte, {byte};
string = quotation_mark, {char}, quotation_mark;

(*comment's part*)
comments = '/', '*', {char | quotation_mark}, '*', '/';

(* Syntax part *)
sst    = record;
record = id, {value}, record_end;
value  = code | string | record;